name: Build

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run lint

  test:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    name: Run test
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm run build
    - name: install webext-agent locally
      run: |
        pnpm pack
        npm install --global webext-agent-*.tgz
    - run: webext-agent install
    - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm run test
      if: runner.os == 'Linux'
    - run: pnpm run test
      if: runner.os != 'Linux'

  publish:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master'
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        command: manifest
    - uses: actions/checkout@v3
      if: ${{ steps.release.outputs.release_created }}
    - uses: pnpm/action-setup@v2
      if: ${{ steps.release.outputs.release_created }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm install --frozen-lockfile
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm run build
      if: ${{ steps.release.outputs.release_created }}
    - run: pnpm publish --new-version $(jq -r .version <package.json)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: ${{ steps.release.outputs.release_created }}
